//
// CursorPaginationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CursorPaginationInfo: Codable, JSONEncodable, Hashable {

    /** URL to retrieve next page of entries */
    public var nextUrl: String?
    /** The cursor ID of the next page */
    public var nextCursor: String?

    public init(nextUrl: String? = nil, nextCursor: String? = nil) {
        self.nextUrl = nextUrl
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nextUrl = "next_url"
        case nextCursor = "next_cursor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nextUrl, forKey: .nextUrl)
        try container.encodeIfPresent(nextCursor, forKey: .nextCursor)
    }
}

