//
// IdPaginationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IdPaginationInfo: Codable, JSONEncodable, Hashable {

    /** URL to retrieve next page of entries */
    public var nextUrl: String?
    /** The max ID of the next page */
    public var nextMaxId: String?

    public init(nextUrl: String? = nil, nextMaxId: String? = nil) {
        self.nextUrl = nextUrl
        self.nextMaxId = nextMaxId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nextUrl = "next_url"
        case nextMaxId = "next_max_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(nextUrl, forKey: .nextUrl)
        try container.encodeIfPresent(nextMaxId, forKey: .nextMaxId)
    }
}

