//
// ImageInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageInfo: Codable, JSONEncodable, Hashable {

    /** URL of the image/video resource */
    public var url: String?
    /** Image/video width in pixels */
    public var width: Int?
    /** Image/video height in pixels */
    public var height: Int?

    public init(url: String? = nil, width: Int? = nil, height: Int? = nil) {
        self.url = url
        self.width = width
        self.height = height
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case width
        case height
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(width, forKey: .width)
        try container.encodeIfPresent(height, forKey: .height)
    }
}

