//
// LikesCollection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LikesCollection: Codable, JSONEncodable, Hashable {

    /** Nember of likes available, data does not necessary contain all comments */
    public var count: Int?
    /** Collection of users who liked; **warning:** deprecated for Apps [created on or after Nov 17, 2015](http://instagram.com/developer/changelog/) */
    public var data: [UserShortInfo]?

    public init(count: Int? = nil, data: [UserShortInfo]? = nil) {
        self.count = count
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

