//
// LocationInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LocationInfo: Codable, JSONEncodable, Hashable {

    /** ID of this location (in some responses it has a type of 'integer') */
    public var id: String?
    /** Location latitude */
    public var latitude: Double?
    /** Location longitude */
    public var longitude: Double?
    /** Location name */
    public var name: String?

    public init(id: String? = nil, latitude: Double? = nil, longitude: Double? = nil, name: String? = nil) {
        self.id = id
        self.latitude = latitude
        self.longitude = longitude
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case latitude
        case longitude
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

