//
// RelationshipStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RelationshipStatus: Codable, JSONEncodable, Hashable {

    public enum OutgoingStatus: String, Codable, CaseIterable {
        case _none = "none"
        case follows = "follows"
        case requested = "requested"
    }
    /** Status of outgoing relationship */
    public var outgoingStatus: OutgoingStatus?

    public init(outgoingStatus: OutgoingStatus? = nil) {
        self.outgoingStatus = outgoingStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outgoingStatus = "outgoing_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(outgoingStatus, forKey: .outgoingStatus)
    }
}

