//
// TagInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TagInfo: Codable, JSONEncodable, Hashable {

    /** Overall number of media entries taged with this name */
    public var mediaCount: Int64?
    /** Tag name */
    public var name: String?

    public init(mediaCount: Int64? = nil, name: String? = nil) {
        self.mediaCount = mediaCount
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mediaCount = "media_count"
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mediaCount, forKey: .mediaCount)
        try container.encodeIfPresent(name, forKey: .name)
    }
}

