//
// UserShortInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserShortInfo: Codable, JSONEncodable, Hashable {

    /** User ID */
    public var id: String?
    /** User name, nickname */
    public var username: String?
    /** URL to user profile picture */
    public var profilePicture: String?
    /** User full name */
    public var fullName: String?

    public init(id: String? = nil, username: String? = nil, profilePicture: String? = nil, fullName: String? = nil) {
        self.id = id
        self.username = username
        self.profilePicture = profilePicture
        self.fullName = fullName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case profilePicture = "profile_picture"
        case fullName = "full_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(profilePicture, forKey: .profilePicture)
        try container.encodeIfPresent(fullName, forKey: .fullName)
    }
}

