//
// UserCounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserCounts: Codable, JSONEncodable, Hashable {

    /** Number of user media */
    public var media: Int?
    /** Number of users followed by this user */
    public var follows: Int?
    /** Number of followers of this user */
    public var followedBy: Int?

    public init(media: Int? = nil, follows: Int? = nil, followedBy: Int? = nil) {
        self.media = media
        self.follows = follows
        self.followedBy = followedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case media
        case follows
        case followedBy = "followed_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(media, forKey: .media)
        try container.encodeIfPresent(follows, forKey: .follows)
        try container.encodeIfPresent(followedBy, forKey: .followedBy)
    }
}

