//
// UserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserInfo: Codable, JSONEncodable, Hashable {

    /** User ID */
    public var id: String?
    /** User name, nickname */
    public var username: String?
    /** User biography */
    public var bio: String?
    /** URL to user web-site */
    public var website: String?
    /** URL to user profile picture */
    public var profilePicture: String?
    /** User full name */
    public var fullName: String?
    public var counts: UserCounts?

    public init(id: String? = nil, username: String? = nil, bio: String? = nil, website: String? = nil, profilePicture: String? = nil, fullName: String? = nil, counts: UserCounts? = nil) {
        self.id = id
        self.username = username
        self.bio = bio
        self.website = website
        self.profilePicture = profilePicture
        self.fullName = fullName
        self.counts = counts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case bio
        case website
        case profilePicture = "profile_picture"
        case fullName = "full_name"
        case counts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(bio, forKey: .bio)
        try container.encodeIfPresent(website, forKey: .website)
        try container.encodeIfPresent(profilePicture, forKey: .profilePicture)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(counts, forKey: .counts)
    }
}

