//
// UsersPagingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersPagingResponse: Codable, JSONEncodable, Hashable {

    public var pagination: CursorPaginationInfo?
    public var meta: MetaData?
    /** List of user short information entries */
    public var data: [UserShortInfo]?

    public init(pagination: CursorPaginationInfo? = nil, meta: MetaData? = nil, data: [UserShortInfo]? = nil) {
        self.pagination = pagination
        self.meta = meta
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case meta
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pagination, forKey: .pagination)
        try container.encodeIfPresent(meta, forKey: .meta)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

